### ISSUE TITLE
DataException: The key for the record cannot be null

### ISSUE THREAD

**Issue by EuphoriaCelestial** [jcustenborder/kafka-connect-redis#46]
My connector encountered this error:

```
[2022-10-17 15:36:25,133] ERROR [sink|task-0] WorkerSinkTask{id=sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: The key for the record cannot be null. topic = redis-test partition = 0 offset = 0 (org.apache.kafka.connect.runtime.WorkerSinkTask:609)
org.apache.kafka.connect.errors.DataException: The key for the record cannot be null. topic = redis-test partition = 0 offset = 0
        at com.github.jcustenborder.kafka.connect.redis.RedisSinkTask.put(RedisSinkTask.java:152)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:244)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
[2022-10-17 15:36:25,373] ERROR [sink|task-0] WorkerSinkTask{id=sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:196)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:611)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:244)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.connect.errors.DataException: The key for the record cannot be null. topic = redis-test partition = 0 offset = 0
```

My guess is I haven't config key-value for Redis and/or my records from Kafka is not in right format, currently, I just read lines from a ` test.txt` file, and the file look like this:
```
foo
bar
another line
line
...
```

And I don't understand the note in README about what format does Kafka records have to be in, can you please explain how to do it? sorry for tagging you, but I need this a little urgent @jcustenborder

**Comment by jcustenborder** [comment]
@EuphoriaCelestial This connector requires a key. When you write data to kafka you can write with a key and value. This connector uses the key in kafka as the key in redis. This connector uses the ByteArrayConverter for the value converter. This means it's just grabbing the bytes from the value in the kafka record, and putting that as the value to be written to redis. The key can either be a String or Bytes. 

All this said you're going to need to key the data in Kafka or use a SMT to key the data on the fly.

**Comment by samehif** [comment]
can you give an example of how to use an SMT to key the data on the fly?
